// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.6
// source: api/lattice/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataplaneKind int32

const (
	DataplaneKind_DATAPLANE_KIND_UNSPECIFIED      DataplaneKind = 0
	DataplaneKind_DATAPLANE_KIND_INFERENCE_ROUTER DataplaneKind = 1
	DataplaneKind_DATAPLANE_KIND_AI_AGENT         DataplaneKind = 2
)

// Enum value maps for DataplaneKind.
var (
	DataplaneKind_name = map[int32]string{
		0: "DATAPLANE_KIND_UNSPECIFIED",
		1: "DATAPLANE_KIND_INFERENCE_ROUTER",
		2: "DATAPLANE_KIND_AI_AGENT",
	}
	DataplaneKind_value = map[string]int32{
		"DATAPLANE_KIND_UNSPECIFIED":      0,
		"DATAPLANE_KIND_INFERENCE_ROUTER": 1,
		"DATAPLANE_KIND_AI_AGENT":         2,
	}
)

func (x DataplaneKind) Enum() *DataplaneKind {
	p := new(DataplaneKind)
	*p = x
	return p
}

func (x DataplaneKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataplaneKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_lattice_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (DataplaneKind) Type() protoreflect.EnumType {
	return &file_api_lattice_control_v1_control_proto_enumTypes[0]
}

func (x DataplaneKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataplaneKind.Descriptor instead.
func (DataplaneKind) EnumDescriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type Subscribe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical catalog service and its concrete running dataplane instance.
	// Both are required; the server must authorize them against the connection identity.
	ServiceId         string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceInstanceId string `protobuf:"bytes,2,opt,name=service_instance_id,json=serviceInstanceId,proto3" json:"service_instance_id,omitempty"`
	// Last generation with BOTH xDS and dataplane configuration stored successfully.
	// Empty on first connection or when their versions differ; requests a full replay.
	// This is a delivery checkpoint, not confirmation of Envoy ACK/readiness.
	LastDataplaneVersion string `protobuf:"bytes,3,opt,name=last_dataplane_version,json=lastDataplaneVersion,proto3" json:"last_dataplane_version,omitempty"`
	SchemaVersion        uint32 `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Identifies the type of dataplane subscribing.
	Kind          DataplaneKind `protobuf:"varint,5,opt,name=kind,proto3,enum=lattice.control.v1.DataplaneKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Subscribe) GetServiceInstanceId() string {
	if x != nil {
		return x.ServiceInstanceId
	}
	return ""
}

func (x *Subscribe) GetLastDataplaneVersion() string {
	if x != nil {
		return x.LastDataplaneVersion
	}
	return ""
}

func (x *Subscribe) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Subscribe) GetKind() DataplaneKind {
	if x != nil {
		return x.Kind
	}
	return DataplaneKind_DATAPLANE_KIND_UNSPECIFIED
}

type DataplaneMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DataplaneMessage_Subscribe
	//	*DataplaneMessage_UpdateStatus
	//	*DataplaneMessage_EnvoyStatus
	Payload       isDataplaneMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataplaneMessage) Reset() {
	*x = DataplaneMessage{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataplaneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataplaneMessage) ProtoMessage() {}

func (x *DataplaneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataplaneMessage.ProtoReflect.Descriptor instead.
func (*DataplaneMessage) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *DataplaneMessage) GetPayload() isDataplaneMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataplaneMessage) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Payload.(*DataplaneMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *DataplaneMessage) GetUpdateStatus() *UpdateStatus {
	if x != nil {
		if x, ok := x.Payload.(*DataplaneMessage_UpdateStatus); ok {
			return x.UpdateStatus
		}
	}
	return nil
}

func (x *DataplaneMessage) GetEnvoyStatus() *EnvoyStatus {
	if x != nil {
		if x, ok := x.Payload.(*DataplaneMessage_EnvoyStatus); ok {
			return x.EnvoyStatus
		}
	}
	return nil
}

type isDataplaneMessage_Payload interface {
	isDataplaneMessage_Payload()
}

type DataplaneMessage_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type DataplaneMessage_UpdateStatus struct {
	UpdateStatus *UpdateStatus `protobuf:"bytes,2,opt,name=update_status,json=updateStatus,proto3,oneof"`
}

type DataplaneMessage_EnvoyStatus struct {
	EnvoyStatus *EnvoyStatus `protobuf:"bytes,3,opt,name=envoy_status,json=envoyStatus,proto3,oneof"`
}

func (*DataplaneMessage_Subscribe) isDataplaneMessage_Payload() {}

func (*DataplaneMessage_UpdateStatus) isDataplaneMessage_Payload() {}

func (*DataplaneMessage_EnvoyStatus) isDataplaneMessage_Payload() {}

type ControlPlaneMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique within a stream; echoed in UpdateStatus. Versions are opaque and
	// immutable. Both payload types for one generation must use the same version.
	// On an empty resume checkpoint, send both complete payloads. Stage dataplane
	// configuration before xDS. Resending identical content renews freshness.
	Nonce string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlPlaneMessage_XdsConfiguration
	//	*ControlPlaneMessage_DataplaneConfiguration
	Payload       isControlPlaneMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlaneMessage) Reset() {
	*x = ControlPlaneMessage{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneMessage) ProtoMessage() {}

func (x *ControlPlaneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneMessage.ProtoReflect.Descriptor instead.
func (*ControlPlaneMessage) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ControlPlaneMessage) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ControlPlaneMessage) GetPayload() isControlPlaneMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlPlaneMessage) GetXdsConfiguration() *XdsConfiguration {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_XdsConfiguration); ok {
			return x.XdsConfiguration
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetDataplaneConfiguration() *DataplaneConfiguration {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_DataplaneConfiguration); ok {
			return x.DataplaneConfiguration
		}
	}
	return nil
}

type isControlPlaneMessage_Payload interface {
	isControlPlaneMessage_Payload()
}

type ControlPlaneMessage_XdsConfiguration struct {
	XdsConfiguration *XdsConfiguration `protobuf:"bytes,2,opt,name=xds_configuration,json=xdsConfiguration,proto3,oneof"`
}

type ControlPlaneMessage_DataplaneConfiguration struct {
	DataplaneConfiguration *DataplaneConfiguration `protobuf:"bytes,3,opt,name=dataplane_configuration,json=dataplaneConfiguration,proto3,oneof"`
}

func (*ControlPlaneMessage_XdsConfiguration) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_DataplaneConfiguration) isControlPlaneMessage_Payload() {}

type ResourceSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Resources     []*anypb.Any           `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSet) Reset() {
	*x = ResourceSet{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSet) ProtoMessage() {}

func (x *ResourceSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSet.ProtoReflect.Descriptor instead.
func (*ResourceSet) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceSet) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *ResourceSet) GetResources() []*anypb.Any {
	if x != nil {
		return x.Resources
	}
	return nil
}

type XdsConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shares the generation version with DataplaneConfiguration.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Complete state-of-the-world CDS, EDS, LDS and RDS bundle. Missing sets
	// mean empty sets, not patches. SDS and mesh-owned secrets are unsupported.
	ResourceSets  []*ResourceSet `protobuf:"bytes,2,rep,name=resource_sets,json=resourceSets,proto3" json:"resource_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XdsConfiguration) Reset() {
	*x = XdsConfiguration{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XdsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XdsConfiguration) ProtoMessage() {}

func (x *XdsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XdsConfiguration.ProtoReflect.Descriptor instead.
func (*XdsConfiguration) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *XdsConfiguration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *XdsConfiguration) GetResourceSets() []*ResourceSet {
	if x != nil {
		return x.ResourceSets
	}
	return nil
}

type DataplaneConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must match trusted x-iir-route-generation gRPC initial metadata in RDS.
	Version       string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Models        []*Model `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataplaneConfiguration) Reset() {
	*x = DataplaneConfiguration{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataplaneConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataplaneConfiguration) ProtoMessage() {}

func (x *DataplaneConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataplaneConfiguration.ProtoReflect.Descriptor instead.
func (*DataplaneConfiguration) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *DataplaneConfiguration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DataplaneConfiguration) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	UpstreamModel string                 `protobuf:"bytes,2,opt,name=upstream_model,json=upstreamModel,proto3" json:"upstream_model,omitempty"`
	// Exact x-iir-model header token matched by the corresponding Envoy route.
	RouteToken        string `protobuf:"bytes,3,opt,name=route_token,json=routeToken,proto3" json:"route_token,omitempty"`
	Enabled           bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SupportsStreaming bool   `protobuf:"varint,5,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	SupportsTools     bool   `protobuf:"varint,6,opt,name=supports_tools,json=supportsTools,proto3" json:"supports_tools,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Model) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Model) GetUpstreamModel() string {
	if x != nil {
		return x.UpstreamModel
	}
	return ""
}

func (x *Model) GetRouteToken() string {
	if x != nil {
		return x.RouteToken
	}
	return ""
}

func (x *Model) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Model) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *Model) GetSupportsTools() bool {
	if x != nil {
		return x.SupportsTools
	}
	return false
}

type UpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`      // "xds" or "dataplane"
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"` // Validated and stored in memory; NOT an Envoy ACK.
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`        // Bounded diagnostic; never raw configuration or prompts.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatus) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *UpdateStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateStatus) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UpdateStatus) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpdateStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EnvoyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	TypeUrl       string                 `protobuf:"bytes,2,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvoyStatus) Reset() {
	*x = EnvoyStatus{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvoyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvoyStatus) ProtoMessage() {}

func (x *EnvoyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvoyStatus.ProtoReflect.Descriptor instead.
func (*EnvoyStatus) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *EnvoyStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnvoyStatus) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *EnvoyStatus) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *EnvoyStatus) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EnvoyStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_lattice_control_v1_control_proto protoreflect.FileDescriptor

const file_api_lattice_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"$api/lattice/control/v1/control.proto\x12\x12lattice.control.v1\x1a\x19google/protobuf/any.proto\"\xee\x01\n" +
	"\tSubscribe\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12.\n" +
	"\x13service_instance_id\x18\x02 \x01(\tR\x11serviceInstanceId\x124\n" +
	"\x16last_dataplane_version\x18\x03 \x01(\tR\x14lastDataplaneVersion\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\rR\rschemaVersion\x125\n" +
	"\x04kind\x18\x05 \x01(\x0e2!.lattice.control.v1.DataplaneKindR\x04kind\"\xeb\x01\n" +
	"\x10DataplaneMessage\x12=\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1d.lattice.control.v1.SubscribeH\x00R\tsubscribe\x12G\n" +
	"\rupdate_status\x18\x02 \x01(\v2 .lattice.control.v1.UpdateStatusH\x00R\fupdateStatus\x12D\n" +
	"\fenvoy_status\x18\x03 \x01(\v2\x1f.lattice.control.v1.EnvoyStatusH\x00R\venvoyStatusB\t\n" +
	"\apayload\"\xf2\x01\n" +
	"\x13ControlPlaneMessage\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12S\n" +
	"\x11xds_configuration\x18\x02 \x01(\v2$.lattice.control.v1.XdsConfigurationH\x00R\x10xdsConfiguration\x12e\n" +
	"\x17dataplane_configuration\x18\x03 \x01(\v2*.lattice.control.v1.DataplaneConfigurationH\x00R\x16dataplaneConfigurationB\t\n" +
	"\apayload\"\\\n" +
	"\vResourceSet\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x122\n" +
	"\tresources\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\tresources\"r\n" +
	"\x10XdsConfiguration\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12D\n" +
	"\rresource_sets\x18\x02 \x03(\v2\x1f.lattice.control.v1.ResourceSetR\fresourceSets\"e\n" +
	"\x16DataplaneConfiguration\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x121\n" +
	"\x06models\x18\x02 \x03(\v2\x19.lattice.control.v1.ModelR\x06models\"\xd5\x01\n" +
	"\x05Model\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12%\n" +
	"\x0eupstream_model\x18\x02 \x01(\tR\rupstreamModel\x12\x1f\n" +
	"\vroute_token\x18\x03 \x01(\tR\n" +
	"routeToken\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12-\n" +
	"\x12supports_streaming\x18\x05 \x01(\bR\x11supportsStreaming\x12%\n" +
	"\x0esupports_tools\x18\x06 \x01(\bR\rsupportsTools\"\x88\x01\n" +
	"\fUpdateStatus\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x8a\x01\n" +
	"\vEnvoyStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\btype_url\x18\x02 \x01(\tR\atypeUrl\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*q\n" +
	"\rDataplaneKind\x12\x1e\n" +
	"\x1aDATAPLANE_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fDATAPLANE_KIND_INFERENCE_ROUTER\x10\x01\x12\x1b\n" +
	"\x17DATAPLANE_KIND_AI_AGENT\x10\x022\x8b\x01\n" +
	"\x13ControlPlaneService\x12t\n" +
	"\x1fSubscribeDataplaneConfiguration\x12$.lattice.control.v1.DataplaneMessage\x1a'.lattice.control.v1.ControlPlaneMessage(\x010\x01BMZKgithub.com/latticecorp/lattice4all/ai-libs/api/lattice/control/v1;controlv1b\x06proto3"

var (
	file_api_lattice_control_v1_control_proto_rawDescOnce sync.Once
	file_api_lattice_control_v1_control_proto_rawDescData []byte
)

func file_api_lattice_control_v1_control_proto_rawDescGZIP() []byte {
	file_api_lattice_control_v1_control_proto_rawDescOnce.Do(func() {
		file_api_lattice_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lattice_control_v1_control_proto_rawDesc), len(file_api_lattice_control_v1_control_proto_rawDesc)))
	})
	return file_api_lattice_control_v1_control_proto_rawDescData
}

var file_api_lattice_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_lattice_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_lattice_control_v1_control_proto_goTypes = []any{
	(DataplaneKind)(0),             // 0: lattice.control.v1.DataplaneKind
	(*Subscribe)(nil),              // 1: lattice.control.v1.Subscribe
	(*DataplaneMessage)(nil),       // 2: lattice.control.v1.DataplaneMessage
	(*ControlPlaneMessage)(nil),    // 3: lattice.control.v1.ControlPlaneMessage
	(*ResourceSet)(nil),            // 4: lattice.control.v1.ResourceSet
	(*XdsConfiguration)(nil),       // 5: lattice.control.v1.XdsConfiguration
	(*DataplaneConfiguration)(nil), // 6: lattice.control.v1.DataplaneConfiguration
	(*Model)(nil),                  // 7: lattice.control.v1.Model
	(*UpdateStatus)(nil),           // 8: lattice.control.v1.UpdateStatus
	(*EnvoyStatus)(nil),            // 9: lattice.control.v1.EnvoyStatus
	(*anypb.Any)(nil),              // 10: google.protobuf.Any
}
var file_api_lattice_control_v1_control_proto_depIdxs = []int32{
	0,  // 0: lattice.control.v1.Subscribe.kind:type_name -> lattice.control.v1.DataplaneKind
	1,  // 1: lattice.control.v1.DataplaneMessage.subscribe:type_name -> lattice.control.v1.Subscribe
	8,  // 2: lattice.control.v1.DataplaneMessage.update_status:type_name -> lattice.control.v1.UpdateStatus
	9,  // 3: lattice.control.v1.DataplaneMessage.envoy_status:type_name -> lattice.control.v1.EnvoyStatus
	5,  // 4: lattice.control.v1.ControlPlaneMessage.xds_configuration:type_name -> lattice.control.v1.XdsConfiguration
	6,  // 5: lattice.control.v1.ControlPlaneMessage.dataplane_configuration:type_name -> lattice.control.v1.DataplaneConfiguration
	10, // 6: lattice.control.v1.ResourceSet.resources:type_name -> google.protobuf.Any
	4,  // 7: lattice.control.v1.XdsConfiguration.resource_sets:type_name -> lattice.control.v1.ResourceSet
	7,  // 8: lattice.control.v1.DataplaneConfiguration.models:type_name -> lattice.control.v1.Model
	2,  // 9: lattice.control.v1.ControlPlaneService.SubscribeDataplaneConfiguration:input_type -> lattice.control.v1.DataplaneMessage
	3,  // 10: lattice.control.v1.ControlPlaneService.SubscribeDataplaneConfiguration:output_type -> lattice.control.v1.ControlPlaneMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_lattice_control_v1_control_proto_init() }
func file_api_lattice_control_v1_control_proto_init() {
	if File_api_lattice_control_v1_control_proto != nil {
		return
	}
	file_api_lattice_control_v1_control_proto_msgTypes[1].OneofWrappers = []any{
		(*DataplaneMessage_Subscribe)(nil),
		(*DataplaneMessage_UpdateStatus)(nil),
		(*DataplaneMessage_EnvoyStatus)(nil),
	}
	file_api_lattice_control_v1_control_proto_msgTypes[2].OneofWrappers = []any{
		(*ControlPlaneMessage_XdsConfiguration)(nil),
		(*ControlPlaneMessage_DataplaneConfiguration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lattice_control_v1_control_proto_rawDesc), len(file_api_lattice_control_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lattice_control_v1_control_proto_goTypes,
		DependencyIndexes: file_api_lattice_control_v1_control_proto_depIdxs,
		EnumInfos:         file_api_lattice_control_v1_control_proto_enumTypes,
		MessageInfos:      file_api_lattice_control_v1_control_proto_msgTypes,
	}.Build()
	File_api_lattice_control_v1_control_proto = out.File
	file_api_lattice_control_v1_control_proto_goTypes = nil
	file_api_lattice_control_v1_control_proto_depIdxs = nil
}
