// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: api/lattice/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_SubscribeDataplaneConfiguration_FullMethodName = "/lattice.control.v1.ControlPlaneService/SubscribeDataplaneConfiguration"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dataplane configuration delivery protocol, distinct from Envoy ADS.
// The development server implements this; lattice-cp currently serves CatalogService.
type ControlPlaneServiceClient interface {
	SubscribeDataplaneConfiguration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataplaneMessage, ControlPlaneMessage], error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) SubscribeDataplaneConfiguration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataplaneMessage, ControlPlaneMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[0], ControlPlaneService_SubscribeDataplaneConfiguration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataplaneMessage, ControlPlaneMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_SubscribeDataplaneConfigurationClient = grpc.BidiStreamingClient[DataplaneMessage, ControlPlaneMessage]

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// Dataplane configuration delivery protocol, distinct from Envoy ADS.
// The development server implements this; lattice-cp currently serves CatalogService.
type ControlPlaneServiceServer interface {
	SubscribeDataplaneConfiguration(grpc.BidiStreamingServer[DataplaneMessage, ControlPlaneMessage]) error
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) SubscribeDataplaneConfiguration(grpc.BidiStreamingServer[DataplaneMessage, ControlPlaneMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeDataplaneConfiguration not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_SubscribeDataplaneConfiguration_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServiceServer).SubscribeDataplaneConfiguration(&grpc.GenericServerStream[DataplaneMessage, ControlPlaneMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_SubscribeDataplaneConfigurationServer = grpc.BidiStreamingServer[DataplaneMessage, ControlPlaneMessage]

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lattice.control.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeDataplaneConfiguration",
			Handler:       _ControlPlaneService_SubscribeDataplaneConfiguration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/lattice/control/v1/control.proto",
}
