// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/lattice/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscribe struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RouterId          string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	LastXdsVersion    string                 `protobuf:"bytes,2,opt,name=last_xds_version,json=lastXdsVersion,proto3" json:"last_xds_version,omitempty"`
	LastRouterVersion string                 `protobuf:"bytes,3,opt,name=last_router_version,json=lastRouterVersion,proto3" json:"last_router_version,omitempty"`
	SchemaVersion     uint32                 `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *Subscribe) GetLastXdsVersion() string {
	if x != nil {
		return x.LastXdsVersion
	}
	return ""
}

func (x *Subscribe) GetLastRouterVersion() string {
	if x != nil {
		return x.LastRouterVersion
	}
	return ""
}

func (x *Subscribe) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type RouterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RouterMessage_Subscribe
	//	*RouterMessage_UpdateStatus
	//	*RouterMessage_EnvoyStatus
	Payload       isRouterMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterMessage) Reset() {
	*x = RouterMessage{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterMessage) ProtoMessage() {}

func (x *RouterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterMessage.ProtoReflect.Descriptor instead.
func (*RouterMessage) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RouterMessage) GetPayload() isRouterMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RouterMessage) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Payload.(*RouterMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *RouterMessage) GetUpdateStatus() *UpdateStatus {
	if x != nil {
		if x, ok := x.Payload.(*RouterMessage_UpdateStatus); ok {
			return x.UpdateStatus
		}
	}
	return nil
}

func (x *RouterMessage) GetEnvoyStatus() *EnvoyStatus {
	if x != nil {
		if x, ok := x.Payload.(*RouterMessage_EnvoyStatus); ok {
			return x.EnvoyStatus
		}
	}
	return nil
}

type isRouterMessage_Payload interface {
	isRouterMessage_Payload()
}

type RouterMessage_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type RouterMessage_UpdateStatus struct {
	UpdateStatus *UpdateStatus `protobuf:"bytes,2,opt,name=update_status,json=updateStatus,proto3,oneof"`
}

type RouterMessage_EnvoyStatus struct {
	EnvoyStatus *EnvoyStatus `protobuf:"bytes,3,opt,name=envoy_status,json=envoyStatus,proto3,oneof"`
}

func (*RouterMessage_Subscribe) isRouterMessage_Payload() {}

func (*RouterMessage_UpdateStatus) isRouterMessage_Payload() {}

func (*RouterMessage_EnvoyStatus) isRouterMessage_Payload() {}

type ControlPlaneMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique within a stream; echoed in UpdateStatus. Versions are opaque and
	// immutable. Resending an identical version refreshes its freshness lease.
	Nonce string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlPlaneMessage_XdsConfiguration
	//	*ControlPlaneMessage_RouterConfiguration
	Payload       isControlPlaneMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlaneMessage) Reset() {
	*x = ControlPlaneMessage{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneMessage) ProtoMessage() {}

func (x *ControlPlaneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneMessage.ProtoReflect.Descriptor instead.
func (*ControlPlaneMessage) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ControlPlaneMessage) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ControlPlaneMessage) GetPayload() isControlPlaneMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlPlaneMessage) GetXdsConfiguration() *XdsConfiguration {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_XdsConfiguration); ok {
			return x.XdsConfiguration
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetRouterConfiguration() *RouterConfiguration {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_RouterConfiguration); ok {
			return x.RouterConfiguration
		}
	}
	return nil
}

type isControlPlaneMessage_Payload interface {
	isControlPlaneMessage_Payload()
}

type ControlPlaneMessage_XdsConfiguration struct {
	XdsConfiguration *XdsConfiguration `protobuf:"bytes,2,opt,name=xds_configuration,json=xdsConfiguration,proto3,oneof"`
}

type ControlPlaneMessage_RouterConfiguration struct {
	RouterConfiguration *RouterConfiguration `protobuf:"bytes,3,opt,name=router_configuration,json=routerConfiguration,proto3,oneof"`
}

func (*ControlPlaneMessage_XdsConfiguration) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_RouterConfiguration) isControlPlaneMessage_Payload() {}

type ResourceSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Resources     []*anypb.Any           `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSet) Reset() {
	*x = ResourceSet{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSet) ProtoMessage() {}

func (x *ResourceSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSet.ProtoReflect.Descriptor instead.
func (*ResourceSet) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceSet) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *ResourceSet) GetResources() []*anypb.Any {
	if x != nil {
		return x.Resources
	}
	return nil
}

type XdsConfiguration struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Complete state-of-the-world CDS, EDS, LDS and RDS bundle. Missing sets
	// mean empty sets, not patches. SDS and mesh-owned secrets are unsupported.
	ResourceSets  []*ResourceSet `protobuf:"bytes,2,rep,name=resource_sets,json=resourceSets,proto3" json:"resource_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XdsConfiguration) Reset() {
	*x = XdsConfiguration{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XdsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XdsConfiguration) ProtoMessage() {}

func (x *XdsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XdsConfiguration.ProtoReflect.Descriptor instead.
func (*XdsConfiguration) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *XdsConfiguration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *XdsConfiguration) GetResourceSets() []*ResourceSet {
	if x != nil {
		return x.ResourceSets
	}
	return nil
}

type RouterConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must match trusted x-iir-route-generation gRPC initial metadata in RDS.
	Version       string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Models        []*Model `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterConfiguration) Reset() {
	*x = RouterConfiguration{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterConfiguration) ProtoMessage() {}

func (x *RouterConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterConfiguration.ProtoReflect.Descriptor instead.
func (*RouterConfiguration) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *RouterConfiguration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RouterConfiguration) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	UpstreamModel string                 `protobuf:"bytes,2,opt,name=upstream_model,json=upstreamModel,proto3" json:"upstream_model,omitempty"`
	// Exact x-iir-model header token matched by the corresponding Envoy route.
	RouteToken        string `protobuf:"bytes,3,opt,name=route_token,json=routeToken,proto3" json:"route_token,omitempty"`
	Enabled           bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SupportsStreaming bool   `protobuf:"varint,5,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	SupportsTools     bool   `protobuf:"varint,6,opt,name=supports_tools,json=supportsTools,proto3" json:"supports_tools,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Model) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Model) GetUpstreamModel() string {
	if x != nil {
		return x.UpstreamModel
	}
	return ""
}

func (x *Model) GetRouteToken() string {
	if x != nil {
		return x.RouteToken
	}
	return ""
}

func (x *Model) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Model) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *Model) GetSupportsTools() bool {
	if x != nil {
		return x.SupportsTools
	}
	return false
}

type UpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`      // "xds" or "router"
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"` // Validated and stored in memory; NOT an Envoy ACK.
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`        // Bounded diagnostic; never raw configuration or prompts.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatus) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *UpdateStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateStatus) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UpdateStatus) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpdateStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EnvoyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	TypeUrl       string                 `protobuf:"bytes,2,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvoyStatus) Reset() {
	*x = EnvoyStatus{}
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvoyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvoyStatus) ProtoMessage() {}

func (x *EnvoyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvoyStatus.ProtoReflect.Descriptor instead.
func (*EnvoyStatus) Descriptor() ([]byte, []int) {
	return file_api_lattice_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *EnvoyStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnvoyStatus) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *EnvoyStatus) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *EnvoyStatus) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EnvoyStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_lattice_control_v1_control_proto protoreflect.FileDescriptor

const file_api_lattice_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"$api/lattice/control/v1/control.proto\x12\x12lattice.control.v1\x1a\x19google/protobuf/any.proto\"\xa9\x01\n" +
	"\tSubscribe\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12(\n" +
	"\x10last_xds_version\x18\x02 \x01(\tR\x0elastXdsVersion\x12.\n" +
	"\x13last_router_version\x18\x03 \x01(\tR\x11lastRouterVersion\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\rR\rschemaVersion\"\xe8\x01\n" +
	"\rRouterMessage\x12=\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1d.lattice.control.v1.SubscribeH\x00R\tsubscribe\x12G\n" +
	"\rupdate_status\x18\x02 \x01(\v2 .lattice.control.v1.UpdateStatusH\x00R\fupdateStatus\x12D\n" +
	"\fenvoy_status\x18\x03 \x01(\v2\x1f.lattice.control.v1.EnvoyStatusH\x00R\venvoyStatusB\t\n" +
	"\apayload\"\xe9\x01\n" +
	"\x13ControlPlaneMessage\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12S\n" +
	"\x11xds_configuration\x18\x02 \x01(\v2$.lattice.control.v1.XdsConfigurationH\x00R\x10xdsConfiguration\x12\\\n" +
	"\x14router_configuration\x18\x03 \x01(\v2'.lattice.control.v1.RouterConfigurationH\x00R\x13routerConfigurationB\t\n" +
	"\apayload\"\\\n" +
	"\vResourceSet\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x122\n" +
	"\tresources\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\tresources\"r\n" +
	"\x10XdsConfiguration\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12D\n" +
	"\rresource_sets\x18\x02 \x03(\v2\x1f.lattice.control.v1.ResourceSetR\fresourceSets\"b\n" +
	"\x13RouterConfiguration\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x121\n" +
	"\x06models\x18\x02 \x03(\v2\x19.lattice.control.v1.ModelR\x06models\"\xd5\x01\n" +
	"\x05Model\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12%\n" +
	"\x0eupstream_model\x18\x02 \x01(\tR\rupstreamModel\x12\x1f\n" +
	"\vroute_token\x18\x03 \x01(\tR\n" +
	"routeToken\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12-\n" +
	"\x12supports_streaming\x18\x05 \x01(\bR\x11supportsStreaming\x12%\n" +
	"\x0esupports_tools\x18\x06 \x01(\bR\rsupportsTools\"\x88\x01\n" +
	"\fUpdateStatus\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x8a\x01\n" +
	"\vEnvoyStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\btype_url\x18\x02 \x01(\tR\atypeUrl\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\x85\x01\n" +
	"\x13ControlPlaneService\x12n\n" +
	"\x1cSubscribeRouterConfiguration\x12!.lattice.control.v1.RouterMessage\x1a'.lattice.control.v1.ControlPlaneMessage(\x010\x01BMZKgithub.com/latticecorp/lattice4all/ai-libs/api/lattice/control/v1;controlv1b\x06proto3"

var (
	file_api_lattice_control_v1_control_proto_rawDescOnce sync.Once
	file_api_lattice_control_v1_control_proto_rawDescData []byte
)

func file_api_lattice_control_v1_control_proto_rawDescGZIP() []byte {
	file_api_lattice_control_v1_control_proto_rawDescOnce.Do(func() {
		file_api_lattice_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lattice_control_v1_control_proto_rawDesc), len(file_api_lattice_control_v1_control_proto_rawDesc)))
	})
	return file_api_lattice_control_v1_control_proto_rawDescData
}

var file_api_lattice_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_lattice_control_v1_control_proto_goTypes = []any{
	(*Subscribe)(nil),           // 0: lattice.control.v1.Subscribe
	(*RouterMessage)(nil),       // 1: lattice.control.v1.RouterMessage
	(*ControlPlaneMessage)(nil), // 2: lattice.control.v1.ControlPlaneMessage
	(*ResourceSet)(nil),         // 3: lattice.control.v1.ResourceSet
	(*XdsConfiguration)(nil),    // 4: lattice.control.v1.XdsConfiguration
	(*RouterConfiguration)(nil), // 5: lattice.control.v1.RouterConfiguration
	(*Model)(nil),               // 6: lattice.control.v1.Model
	(*UpdateStatus)(nil),        // 7: lattice.control.v1.UpdateStatus
	(*EnvoyStatus)(nil),         // 8: lattice.control.v1.EnvoyStatus
	(*anypb.Any)(nil),           // 9: google.protobuf.Any
}
var file_api_lattice_control_v1_control_proto_depIdxs = []int32{
	0, // 0: lattice.control.v1.RouterMessage.subscribe:type_name -> lattice.control.v1.Subscribe
	7, // 1: lattice.control.v1.RouterMessage.update_status:type_name -> lattice.control.v1.UpdateStatus
	8, // 2: lattice.control.v1.RouterMessage.envoy_status:type_name -> lattice.control.v1.EnvoyStatus
	4, // 3: lattice.control.v1.ControlPlaneMessage.xds_configuration:type_name -> lattice.control.v1.XdsConfiguration
	5, // 4: lattice.control.v1.ControlPlaneMessage.router_configuration:type_name -> lattice.control.v1.RouterConfiguration
	9, // 5: lattice.control.v1.ResourceSet.resources:type_name -> google.protobuf.Any
	3, // 6: lattice.control.v1.XdsConfiguration.resource_sets:type_name -> lattice.control.v1.ResourceSet
	6, // 7: lattice.control.v1.RouterConfiguration.models:type_name -> lattice.control.v1.Model
	1, // 8: lattice.control.v1.ControlPlaneService.SubscribeRouterConfiguration:input_type -> lattice.control.v1.RouterMessage
	2, // 9: lattice.control.v1.ControlPlaneService.SubscribeRouterConfiguration:output_type -> lattice.control.v1.ControlPlaneMessage
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_lattice_control_v1_control_proto_init() }
func file_api_lattice_control_v1_control_proto_init() {
	if File_api_lattice_control_v1_control_proto != nil {
		return
	}
	file_api_lattice_control_v1_control_proto_msgTypes[1].OneofWrappers = []any{
		(*RouterMessage_Subscribe)(nil),
		(*RouterMessage_UpdateStatus)(nil),
		(*RouterMessage_EnvoyStatus)(nil),
	}
	file_api_lattice_control_v1_control_proto_msgTypes[2].OneofWrappers = []any{
		(*ControlPlaneMessage_XdsConfiguration)(nil),
		(*ControlPlaneMessage_RouterConfiguration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lattice_control_v1_control_proto_rawDesc), len(file_api_lattice_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lattice_control_v1_control_proto_goTypes,
		DependencyIndexes: file_api_lattice_control_v1_control_proto_depIdxs,
		MessageInfos:      file_api_lattice_control_v1_control_proto_msgTypes,
	}.Build()
	File_api_lattice_control_v1_control_proto = out.File
	file_api_lattice_control_v1_control_proto_goTypes = nil
	file_api_lattice_control_v1_control_proto_depIdxs = nil
}
