// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.6
// source: api/lattice/catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Address) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelIds      []string               `protobuf:"bytes,1,rep,name=model_ids,json=modelIDs,proto3" json:"model_ids,omitempty"`
	Protocols     []string               `protobuf:"bytes,2,rep,name=protocols,proto3" json:"protocols,omitempty"`
	ToolNames     []string               `protobuf:"bytes,3,rep,name=tool_names,json=toolNames,proto3" json:"tool_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Capabilities) GetModelIds() []string {
	if x != nil {
		return x.ModelIds
	}
	return nil
}

func (x *Capabilities) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Capabilities) GetToolNames() []string {
	if x != nil {
		return x.ToolNames
	}
	return nil
}

type ServiceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  *Capabilities          `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInput) Reset() {
	*x = ServiceInput{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInput) ProtoMessage() {}

func (x *ServiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInput.ProtoReflect.Descriptor instead.
func (*ServiceInput) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceInput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ServiceInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInput) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ServiceInput) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ServiceInput) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ServiceInput) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  *Capabilities          `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Revision      uint64                 `protobuf:"varint,9,opt,name=revision,proto3" json:"revision,omitempty"`
	Origin        string                 `protobuf:"bytes,10,opt,name=origin,proto3" json:"origin,omitempty"`
	Owner         string                 `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Service) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Service) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Service) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Service) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Service) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Service) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Service) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Service) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Service) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Operation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Service          *ServiceInput          `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	// JSON Merge Patch over editable service fields. Used only by update.
	PatchJson     []byte `protobuf:"bytes,5,opt,name=patch_json,json=patchJson,proto3" json:"patch_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *Operation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *Operation) GetService() *ServiceInput {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Operation) GetPatchJson() []byte {
	if x != nil {
		return x.PatchJson
	}
	return nil
}

type ServiceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceError) Reset() {
	*x = ServiceError{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceError) ProtoMessage() {}

func (x *ServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceError.ProtoReflect.Descriptor instead.
func (*ServiceError) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServiceError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceError) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServiceError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type MutationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestID,proto3" json:"request_id,omitempty"`
	CatalogRevision uint64                 `protobuf:"varint,2,opt,name=catalog_revision,json=catalogRevision,proto3" json:"catalog_revision,omitempty"`
	AppliedIndex    uint64                 `protobuf:"varint,3,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	Services        []*Service             `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	DeletedIds      []string               `protobuf:"bytes,5,rep,name=deleted_ids,json=deletedIDs,proto3" json:"deleted_ids,omitempty"`
	Error           *ServiceError          `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MutationResult) Reset() {
	*x = MutationResult{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResult) ProtoMessage() {}

func (x *MutationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResult.ProtoReflect.Descriptor instead.
func (*MutationResult) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *MutationResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MutationResult) GetCatalogRevision() uint64 {
	if x != nil {
		return x.CatalogRevision
	}
	return 0
}

func (x *MutationResult) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *MutationResult) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *MutationResult) GetDeletedIds() []string {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

func (x *MutationResult) GetError() *ServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

// stale=true means this view may lag the leader. The index/revision identify
// the captured local state; observed_at is the capture time, not a sync promise.
type ReadMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Stale           bool                   `protobuf:"varint,1,opt,name=stale,proto3" json:"stale,omitempty"`
	CatalogRevision uint64                 `protobuf:"varint,2,opt,name=catalog_revision,json=catalogRevision,proto3" json:"catalog_revision,omitempty"`
	AppliedIndex    uint64                 `protobuf:"varint,3,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	ServingNode     string                 `protobuf:"bytes,4,opt,name=serving_node,json=servingNode,proto3" json:"serving_node,omitempty"`
	ObservedAt      string                 `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadMetadata) Reset() {
	*x = ReadMetadata{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMetadata) ProtoMessage() {}

func (x *ReadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMetadata.ProtoReflect.Descriptor instead.
func (*ReadMetadata) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ReadMetadata) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *ReadMetadata) GetCatalogRevision() uint64 {
	if x != nil {
		return x.CatalogRevision
	}
	return 0
}

func (x *ReadMetadata) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *ReadMetadata) GetServingNode() string {
	if x != nil {
		return x.ServingNode
	}
	return ""
}

func (x *ReadMetadata) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

type CreateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInput          `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *CreateServiceRequest) GetService() *ServiceInput {
	if x != nil {
		return x.Service
	}
	return nil
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stale         *bool                  `protobuf:"varint,2,opt,name=stale,proto3,oneof" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *GetServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetServiceRequest) GetStale() bool {
	if x != nil && x.Stale != nil {
		return *x.Stale
	}
	return false
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Read          *ReadMetadata          `protobuf:"bytes,2,opt,name=read,proto3" json:"read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *GetServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *GetServiceResponse) GetRead() *ReadMetadata {
	if x != nil {
		return x.Read
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stale         *bool                  `protobuf:"varint,1,opt,name=stale,proto3,oneof" json:"stale,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Origin        string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit         uint32                 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *ListServicesRequest) GetStale() bool {
	if x != nil && x.Stale != nil {
		return *x.Stale
	}
	return false
}

func (x *ListServicesRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListServicesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListServicesRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ListServicesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListServicesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListServicesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListServicesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Items           []*Service             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor      string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	CatalogRevision uint64                 `protobuf:"varint,3,opt,name=catalog_revision,json=catalogRevision,proto3" json:"catalog_revision,omitempty"`
	Read            *ReadMetadata          `protobuf:"bytes,4,opt,name=read,proto3" json:"read,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *ListServicesResponse) GetItems() []*Service {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListServicesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListServicesResponse) GetCatalogRevision() uint64 {
	if x != nil {
		return x.CatalogRevision
	}
	return 0
}

func (x *ListServicesResponse) GetRead() *ReadMetadata {
	if x != nil {
		return x.Read
	}
	return nil
}

type UpdateServiceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	PatchJson        []byte                 `protobuf:"bytes,3,opt,name=patch_json,json=patchJson,proto3" json:"patch_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateServiceRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *UpdateServiceRequest) GetPatchJson() []byte {
	if x != nil {
		return x.PatchJson
	}
	return nil
}

type DeleteServiceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteServiceRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type ApplyTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyTransactionRequest) Reset() {
	*x = ApplyTransactionRequest{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTransactionRequest) ProtoMessage() {}

func (x *ApplyTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTransactionRequest.ProtoReflect.Descriptor instead.
func (*ApplyTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyTransactionRequest) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestID,proto3" json:"request_id,omitempty"`
	Stale         *bool                  `protobuf:"varint,2,opt,name=stale,proto3,oneof" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *GetOperationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetOperationRequest) GetStale() bool {
	if x != nil && x.Stale != nil {
		return *x.Stale
	}
	return false
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *MutationResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Read          *ReadMetadata          `protobuf:"bytes,2,opt,name=read,proto3" json:"read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *GetOperationResponse) GetResult() *MutationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetOperationResponse) GetRead() *ReadMetadata {
	if x != nil {
		return x.Read
	}
	return nil
}

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quorum        bool                   `protobuf:"varint,1,opt,name=quorum,proto3" json:"quorum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *CheckHealthRequest) GetQuorum() bool {
	if x != nil {
		return x.Quorum
	}
	return false
}

type CheckHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeID,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lattice_catalog_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *CheckHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckHealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_api_lattice_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_api_lattice_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"$api/lattice/catalog/v1/catalog.proto\x12\x12lattice.catalog.v1\"3\n" +
	"\aAddress\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"h\n" +
	"\fCapabilities\x12\x1b\n" +
	"\tmodel_ids\x18\x01 \x03(\tR\bmodelIDs\x12\x1c\n" +
	"\tprotocols\x18\x02 \x03(\tR\tprotocols\x12\x1d\n" +
	"\n" +
	"tool_names\x18\x03 \x03(\tR\ttoolNames\"\xce\x02\n" +
	"\fServiceInput\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12D\n" +
	"\x06labels\x18\x04 \x03(\v2,.lattice.catalog.v1.ServiceInput.LabelsEntryR\x06labels\x12D\n" +
	"\fcapabilities\x18\x05 \x01(\v2 .lattice.catalog.v1.CapabilitiesR\fcapabilities\x129\n" +
	"\taddresses\x18\x06 \x03(\v2\x1b.lattice.catalog.v1.AddressR\taddresses\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x04\n" +
	"\aService\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12?\n" +
	"\x06labels\x18\x04 \x03(\v2'.lattice.catalog.v1.Service.LabelsEntryR\x06labels\x12D\n" +
	"\fcapabilities\x18\x05 \x01(\v2 .lattice.catalog.v1.CapabilitiesR\fcapabilities\x129\n" +
	"\taddresses\x18\x06 \x03(\v2\x1b.lattice.catalog.v1.AddressR\taddresses\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12%\n" +
	"\x0eschema_version\x18\b \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\brevision\x18\t \x01(\x04R\brevision\x12\x16\n" +
	"\x06origin\x18\n" +
	" \x01(\tR\x06origin\x12\x14\n" +
	"\x05owner\x18\v \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\tOperation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\x12:\n" +
	"\aservice\x18\x04 \x01(\v2 .lattice.catalog.v1.ServiceInputR\aservice\x12\x1d\n" +
	"\n" +
	"patch_json\x18\x05 \x01(\fR\tpatchJson\"\xd9\x01\n" +
	"\fServiceError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12G\n" +
	"\adetails\x18\x04 \x03(\v2-.lattice.catalog.v1.ServiceError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x02\n" +
	"\x0eMutationResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestID\x12)\n" +
	"\x10catalog_revision\x18\x02 \x01(\x04R\x0fcatalogRevision\x12#\n" +
	"\rapplied_index\x18\x03 \x01(\x04R\fappliedIndex\x127\n" +
	"\bservices\x18\x04 \x03(\v2\x1b.lattice.catalog.v1.ServiceR\bservices\x12\x1f\n" +
	"\vdeleted_ids\x18\x05 \x03(\tR\n" +
	"deletedIDs\x126\n" +
	"\x05error\x18\x06 \x01(\v2 .lattice.catalog.v1.ServiceErrorR\x05error\"\xb8\x01\n" +
	"\fReadMetadata\x12\x14\n" +
	"\x05stale\x18\x01 \x01(\bR\x05stale\x12)\n" +
	"\x10catalog_revision\x18\x02 \x01(\x04R\x0fcatalogRevision\x12#\n" +
	"\rapplied_index\x18\x03 \x01(\x04R\fappliedIndex\x12!\n" +
	"\fserving_node\x18\x04 \x01(\tR\vservingNode\x12\x1f\n" +
	"\vobserved_at\x18\x05 \x01(\tR\n" +
	"observedAt\"R\n" +
	"\x14CreateServiceRequest\x12:\n" +
	"\aservice\x18\x01 \x01(\v2 .lattice.catalog.v1.ServiceInputR\aservice\"H\n" +
	"\x11GetServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05stale\x18\x02 \x01(\bH\x00R\x05stale\x88\x01\x01B\b\n" +
	"\x06_stale\"\x81\x01\n" +
	"\x12GetServiceResponse\x125\n" +
	"\aservice\x18\x01 \x01(\v2\x1b.lattice.catalog.v1.ServiceR\aservice\x124\n" +
	"\x04read\x18\x02 \x01(\v2 .lattice.catalog.v1.ReadMetadataR\x04read\"\xb0\x02\n" +
	"\x13ListServicesRequest\x12\x19\n" +
	"\x05stale\x18\x01 \x01(\bH\x00R\x05stale\x88\x01\x01\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12K\n" +
	"\x06labels\x18\x05 \x03(\v23.lattice.catalog.v1.ListServicesRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\a \x01(\tR\x06cursor\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_stale\"\xcb\x01\n" +
	"\x14ListServicesResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.lattice.catalog.v1.ServiceR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12)\n" +
	"\x10catalog_revision\x18\x03 \x01(\x04R\x0fcatalogRevision\x124\n" +
	"\x04read\x18\x04 \x01(\v2 .lattice.catalog.v1.ReadMetadataR\x04read\"r\n" +
	"\x14UpdateServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\x12\x1d\n" +
	"\n" +
	"patch_json\x18\x03 \x01(\fR\tpatchJson\"S\n" +
	"\x14DeleteServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\"X\n" +
	"\x17ApplyTransactionRequest\x12=\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x1d.lattice.catalog.v1.OperationR\n" +
	"operations\"Y\n" +
	"\x13GetOperationRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestID\x12\x19\n" +
	"\x05stale\x18\x02 \x01(\bH\x00R\x05stale\x88\x01\x01B\b\n" +
	"\x06_stale\"\x88\x01\n" +
	"\x14GetOperationResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\v2\".lattice.catalog.v1.MutationResultR\x06result\x124\n" +
	"\x04read\x18\x02 \x01(\v2 .lattice.catalog.v1.ReadMetadataR\x04read\",\n" +
	"\x12CheckHealthRequest\x12\x16\n" +
	"\x06quorum\x18\x01 \x01(\bR\x06quorum\"F\n" +
	"\x13CheckHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeID2\x95\x06\n" +
	"\x0eCatalogService\x12]\n" +
	"\rCreateService\x12(.lattice.catalog.v1.CreateServiceRequest\x1a\".lattice.catalog.v1.MutationResult\x12[\n" +
	"\n" +
	"GetService\x12%.lattice.catalog.v1.GetServiceRequest\x1a&.lattice.catalog.v1.GetServiceResponse\x12a\n" +
	"\fListServices\x12'.lattice.catalog.v1.ListServicesRequest\x1a(.lattice.catalog.v1.ListServicesResponse\x12]\n" +
	"\rUpdateService\x12(.lattice.catalog.v1.UpdateServiceRequest\x1a\".lattice.catalog.v1.MutationResult\x12]\n" +
	"\rDeleteService\x12(.lattice.catalog.v1.DeleteServiceRequest\x1a\".lattice.catalog.v1.MutationResult\x12c\n" +
	"\x10ApplyTransaction\x12+.lattice.catalog.v1.ApplyTransactionRequest\x1a\".lattice.catalog.v1.MutationResult\x12a\n" +
	"\fGetOperation\x12'.lattice.catalog.v1.GetOperationRequest\x1a(.lattice.catalog.v1.GetOperationResponse\x12^\n" +
	"\vCheckHealth\x12&.lattice.catalog.v1.CheckHealthRequest\x1a'.lattice.catalog.v1.CheckHealthResponseBMZKgithub.com/latticecorp/lattice4all/ai-libs/api/lattice/catalog/v1;catalogv1b\x06proto3"

var (
	file_api_lattice_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_api_lattice_catalog_v1_catalog_proto_rawDescData []byte
)

func file_api_lattice_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_api_lattice_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_api_lattice_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lattice_catalog_v1_catalog_proto_rawDesc), len(file_api_lattice_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_api_lattice_catalog_v1_catalog_proto_rawDescData
}

var file_api_lattice_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_lattice_catalog_v1_catalog_proto_goTypes = []any{
	(*Address)(nil),                 // 0: lattice.catalog.v1.Address
	(*Capabilities)(nil),            // 1: lattice.catalog.v1.Capabilities
	(*ServiceInput)(nil),            // 2: lattice.catalog.v1.ServiceInput
	(*Service)(nil),                 // 3: lattice.catalog.v1.Service
	(*Operation)(nil),               // 4: lattice.catalog.v1.Operation
	(*ServiceError)(nil),            // 5: lattice.catalog.v1.ServiceError
	(*MutationResult)(nil),          // 6: lattice.catalog.v1.MutationResult
	(*ReadMetadata)(nil),            // 7: lattice.catalog.v1.ReadMetadata
	(*CreateServiceRequest)(nil),    // 8: lattice.catalog.v1.CreateServiceRequest
	(*GetServiceRequest)(nil),       // 9: lattice.catalog.v1.GetServiceRequest
	(*GetServiceResponse)(nil),      // 10: lattice.catalog.v1.GetServiceResponse
	(*ListServicesRequest)(nil),     // 11: lattice.catalog.v1.ListServicesRequest
	(*ListServicesResponse)(nil),    // 12: lattice.catalog.v1.ListServicesResponse
	(*UpdateServiceRequest)(nil),    // 13: lattice.catalog.v1.UpdateServiceRequest
	(*DeleteServiceRequest)(nil),    // 14: lattice.catalog.v1.DeleteServiceRequest
	(*ApplyTransactionRequest)(nil), // 15: lattice.catalog.v1.ApplyTransactionRequest
	(*GetOperationRequest)(nil),     // 16: lattice.catalog.v1.GetOperationRequest
	(*GetOperationResponse)(nil),    // 17: lattice.catalog.v1.GetOperationResponse
	(*CheckHealthRequest)(nil),      // 18: lattice.catalog.v1.CheckHealthRequest
	(*CheckHealthResponse)(nil),     // 19: lattice.catalog.v1.CheckHealthResponse
	nil,                             // 20: lattice.catalog.v1.ServiceInput.LabelsEntry
	nil,                             // 21: lattice.catalog.v1.Service.LabelsEntry
	nil,                             // 22: lattice.catalog.v1.ServiceError.DetailsEntry
	nil,                             // 23: lattice.catalog.v1.ListServicesRequest.LabelsEntry
}
var file_api_lattice_catalog_v1_catalog_proto_depIdxs = []int32{
	20, // 0: lattice.catalog.v1.ServiceInput.labels:type_name -> lattice.catalog.v1.ServiceInput.LabelsEntry
	1,  // 1: lattice.catalog.v1.ServiceInput.capabilities:type_name -> lattice.catalog.v1.Capabilities
	0,  // 2: lattice.catalog.v1.ServiceInput.addresses:type_name -> lattice.catalog.v1.Address
	21, // 3: lattice.catalog.v1.Service.labels:type_name -> lattice.catalog.v1.Service.LabelsEntry
	1,  // 4: lattice.catalog.v1.Service.capabilities:type_name -> lattice.catalog.v1.Capabilities
	0,  // 5: lattice.catalog.v1.Service.addresses:type_name -> lattice.catalog.v1.Address
	2,  // 6: lattice.catalog.v1.Operation.service:type_name -> lattice.catalog.v1.ServiceInput
	22, // 7: lattice.catalog.v1.ServiceError.details:type_name -> lattice.catalog.v1.ServiceError.DetailsEntry
	3,  // 8: lattice.catalog.v1.MutationResult.services:type_name -> lattice.catalog.v1.Service
	5,  // 9: lattice.catalog.v1.MutationResult.error:type_name -> lattice.catalog.v1.ServiceError
	2,  // 10: lattice.catalog.v1.CreateServiceRequest.service:type_name -> lattice.catalog.v1.ServiceInput
	3,  // 11: lattice.catalog.v1.GetServiceResponse.service:type_name -> lattice.catalog.v1.Service
	7,  // 12: lattice.catalog.v1.GetServiceResponse.read:type_name -> lattice.catalog.v1.ReadMetadata
	23, // 13: lattice.catalog.v1.ListServicesRequest.labels:type_name -> lattice.catalog.v1.ListServicesRequest.LabelsEntry
	3,  // 14: lattice.catalog.v1.ListServicesResponse.items:type_name -> lattice.catalog.v1.Service
	7,  // 15: lattice.catalog.v1.ListServicesResponse.read:type_name -> lattice.catalog.v1.ReadMetadata
	4,  // 16: lattice.catalog.v1.ApplyTransactionRequest.operations:type_name -> lattice.catalog.v1.Operation
	6,  // 17: lattice.catalog.v1.GetOperationResponse.result:type_name -> lattice.catalog.v1.MutationResult
	7,  // 18: lattice.catalog.v1.GetOperationResponse.read:type_name -> lattice.catalog.v1.ReadMetadata
	8,  // 19: lattice.catalog.v1.CatalogService.CreateService:input_type -> lattice.catalog.v1.CreateServiceRequest
	9,  // 20: lattice.catalog.v1.CatalogService.GetService:input_type -> lattice.catalog.v1.GetServiceRequest
	11, // 21: lattice.catalog.v1.CatalogService.ListServices:input_type -> lattice.catalog.v1.ListServicesRequest
	13, // 22: lattice.catalog.v1.CatalogService.UpdateService:input_type -> lattice.catalog.v1.UpdateServiceRequest
	14, // 23: lattice.catalog.v1.CatalogService.DeleteService:input_type -> lattice.catalog.v1.DeleteServiceRequest
	15, // 24: lattice.catalog.v1.CatalogService.ApplyTransaction:input_type -> lattice.catalog.v1.ApplyTransactionRequest
	16, // 25: lattice.catalog.v1.CatalogService.GetOperation:input_type -> lattice.catalog.v1.GetOperationRequest
	18, // 26: lattice.catalog.v1.CatalogService.CheckHealth:input_type -> lattice.catalog.v1.CheckHealthRequest
	6,  // 27: lattice.catalog.v1.CatalogService.CreateService:output_type -> lattice.catalog.v1.MutationResult
	10, // 28: lattice.catalog.v1.CatalogService.GetService:output_type -> lattice.catalog.v1.GetServiceResponse
	12, // 29: lattice.catalog.v1.CatalogService.ListServices:output_type -> lattice.catalog.v1.ListServicesResponse
	6,  // 30: lattice.catalog.v1.CatalogService.UpdateService:output_type -> lattice.catalog.v1.MutationResult
	6,  // 31: lattice.catalog.v1.CatalogService.DeleteService:output_type -> lattice.catalog.v1.MutationResult
	6,  // 32: lattice.catalog.v1.CatalogService.ApplyTransaction:output_type -> lattice.catalog.v1.MutationResult
	17, // 33: lattice.catalog.v1.CatalogService.GetOperation:output_type -> lattice.catalog.v1.GetOperationResponse
	19, // 34: lattice.catalog.v1.CatalogService.CheckHealth:output_type -> lattice.catalog.v1.CheckHealthResponse
	27, // [27:35] is the sub-list for method output_type
	19, // [19:27] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_lattice_catalog_v1_catalog_proto_init() }
func file_api_lattice_catalog_v1_catalog_proto_init() {
	if File_api_lattice_catalog_v1_catalog_proto != nil {
		return
	}
	file_api_lattice_catalog_v1_catalog_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_lattice_catalog_v1_catalog_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_lattice_catalog_v1_catalog_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lattice_catalog_v1_catalog_proto_rawDesc), len(file_api_lattice_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lattice_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_api_lattice_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_api_lattice_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_api_lattice_catalog_v1_catalog_proto = out.File
	file_api_lattice_catalog_v1_catalog_proto_goTypes = nil
	file_api_lattice_catalog_v1_catalog_proto_depIdxs = nil
}
